module.exports = [
  {
    title: 'Original',
    summary: 'A family favorite for years. Its wholesome goodness is good for heart health, too.',
    price: 499,
    inventory: 2000,
    calories: 100,
    sugar: 1,
    fiber: 3,
    protein: 3,
  },
  {
    title: 'Honey Nut',
    summary: 'An irresistable taste of golden honey that also provides 12 essential vitamins and minerals.',
    price: 499,
    inventory: 2000,
    calories: 110,
    sugar: 9,
    fiber: 2,
    protein: 2
  },
  {
    title: 'Multi Grain',
    summary: 'The perfectly balanced combination of nutrition and taste with 5 lightly sweetened whole grains.',
    price: 549,
    inventory: 500,
    calories: 110,
    sugar: 6,
    fiber: 3,
    protein: 2,
  },
  {
    title: 'Apple Cinnamon',
    summary: 'The taste of baked apples and cinnamon made with whole grain makes this cereal a delicious choice.',
    price: 549,
    inventory: 500,
    calories: 120,
    sugar: 10,
    fiber: 2,
    protein: 2,
  },
  {
    title: 'Fruity',
    summary: 'The goodness of Cheerios with the added fun of fruit packed into every O.',
    price: 599,
    inventory: 500,
    calories: 100,
    sugar: 8,
    fiber: 2,
    protein: 2,
  },
  {
    title: 'Frosted',
    summary: 'A delicious, sweet taste that kids love made with whole grains.',
    price: 599,
    inventory: 500,
    calories: 100,
    sugar: 9,
    fiber: 2,
    protein: 2,
  },
  {
    title: 'Protein',
    summary: 'A family favorite for years now has more protein with a taste your whole family will love.',
    price: 699,
    inventory: 500,
    calories: 210,
    sugar: 17,
    fiber: 4,
    protein: 7,
  },
  {
    title: 'Ancient Grains',
    summary: 'The new Cheerios + Ancient Grains has a deliciously sweet taste and the goodness that comes with ancient grains.',
    price: 699,
    inventory: 80,
    calories: 110,
    sugar: 5,
    fiber: 2,
    protein: 3,
  },
  {
    title: 'Pumpkin Spice',
    summary: 'Real pumpkin puree and cinnamon, nutmeg, and clove come together for a delicious fall treat!',
    price: 699,
    inventory: 1000,
    calories: 110,
    sugar: 8,
    fiber: 3,
    protein: 2,
  }
];
